### ISSUE TITLE
audio on base-init does not work

### ISSUE THREAD

**Issue by lshapz** [rwieruch/react-redux-soundcloud#2]
hey! I really enjoyed your tutorial. However, we encountered an error* on the loading of activeTrack in the base-init version. This was true even when we cloned your repo and npm started your version of the application. 

We were able to resolve it by importing the node module redux-audio+ and rendering the track in an Audio component, rather than a plain html audio element. 

You may want to revise the tutorial to mention this? 

*DOMException: Failed to load because no supported source was found
+ https://www.npmjs.com/package/redux-audio

**Comment by rwieruch** [comment]
Sorry for coming back so late to this! I never heard again about this issue. Did you use any particular browser where the problem happened? I wouldn't want to introduce a third-party library, when it would work with the native DOM api.
