### ISSUE TITLE
Redux data

### ISSUE THREAD

**Issue by veeramarni** [rwieruch/react-redux-soundcloud#3]
Is it good to store so much data in the redux store? I have noticed the sample website is already slow. Any tips on limiting data into the store, so it would slow down the browsing.

**Comment by rwieruch** [comment]
I think it is ok to store the data in the Redux store. Where else would you store it? I didn't experience any performance issues. When do they occur for you? When storing more and more tracks when you scroll down? Thanks for your feedback!
